Plan.create("name"=>"Gotham Archery", "location"=>"480 Baltic St Brooklyn, NY 11217", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Gotham Archery", "location"=>"73 Allen St Fl 2 New York, NY 10002", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Hidden Gems Archery", "location"=>"Brooklyn, NY 11201", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Axes And Arrows", "location"=>"47- 11 Van Dam St Long Island City, NY 11101", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Jersey City Archery", "location"=>"7 Sherman Ave Fl 2 Jersey City, NJ 07307", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"La Perla Del Ulua", "location"=>"354 Melrose St Brooklyn, NY 11237", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"El Rey del Sur", "location"=>"115 Bowers St Jersey City, NJ 07307", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Progreso", "location"=>"5303 Fort Hamilton Pkwy New York, NY 11219", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Rinconcito Copaneco", "location"=>"15 Jordan Ave Jersey City, NJ 07306", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Casa Adela", "location"=>"66 Ave C New York, NY 10009", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"El Rinconcito Tipico Hondureno", "location"=>"1224 Bergenline Ave Union City, NJ 07087", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Empanada Mama - Hell's Kitchen", "location"=>"765 9th Ave New York, NY 10019", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Juanita's Restaurant", "location"=>"526 6th St Ste A Union City, NJ 07087", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Restaurant Salvadoreno Usuluteco", "location"=>"4017 5th Ave Brooklyn, NY 11232", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Laboratory Testing", "location"=>"401 Goffle Rd Lab Corp Ridgewood, NJ 07450", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Financial Investigation Services", "location"=>"New York, NY 10308", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Paragon Sports", "location"=>"867 Broadway New York, NY 10003", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"REI", "location"=>"303 Lafayette St New York, NY 10012", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Jane DO - Jersey City Studio", "location"=>"160 Newark Ave Fl 3 Jersey City, NJ 07302", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Equinox Tribeca", "location"=>"54 Murray St New York, NY 10007", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"New York Sports Clubs", "location"=>"30 Broad St Fl 1 New York, NY 10005", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"ZogSports", "location"=>"19 W 36th St Fl 4 New York, NY 10018", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"GYM NYC", "location"=>"227 Mulberry St New York, NY 10012", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Planet Fitness", "location"=>"25 Broadway New York, NY 10004", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Mason's Tennis Mart", "location"=>"56 E 53rd St New York, NY 10022", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Adorama", "location"=>"42 W 18th St New York, NY 10011", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"CompleteBody Financial District", "location"=>"10 Hanover Sq New York, NY 10005", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Just Train", "location"=>"6 Maiden Ln Fl 2 New York, NY 10038", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Equinox Wall Street", "location"=>"14 Wall St New York, NY 10005", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Base", "location"=>"60 Christopher Columbus Dr Jersey City, NJ 07302", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Harbor Fitness", "location"=>"550 5th Ave Brooklyn, NY 11215", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Retro Fitness", "location"=>"1 New York Plz New York, NY 10004", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"JackRabbit - Union Square", "location"=>"42 W 14th St New York, NY 10011", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"New York Golf Center", "location"=>"131 W 35th St New York, NY 10001", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Crunch Fitness - Tribeca", "location"=>"80 Leonard St New York, NY 10013", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"World Boxing Gym", "location"=>"29 Division St Jersey City, NJ 07302", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"B&H Photo Video - Electronics and Camera Store", "location"=>"420 9th Ave New York, NY 10001", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"New York Bartending School", "location"=>"68 W 39th St New York, NY 10018", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Ludlow Fitness", "location"=>"100 Delancey St New York, NY 10002", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Complete by CompleteBody Union Square", "location"=>"25 West 14th St New York, NY 10011", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Mid City Gym", "location"=>"345 W 42nd St New York, NY 10036", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Savelli", "location"=>"195 Smith St New York, NY 11201", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Trattoria Trecolori", "location"=>"254 West 47th St New York, NY 10036", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Trattoria Dell'Arte", "location"=>"900 7th Ave New York, NY 10019", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Stella 34 Trattoria", "location"=>"151 W 34th St Macy's Herald Square New York, NY 10001", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Gnocco", "location"=>"337 E 10th St New York, NY 10009", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Villa Berulia", "location"=>"107 E 34th St New York, NY 10016", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Aurora", "location"=>"70 Grand St Brooklyn, NY 11249", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"The Shoeshine Guild", "location"=>"75 9th Ave Chelsea Market New York, NY 10011", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Esther Shoe Repair", "location"=>"7 Hanover Sq New York, NY 10004", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Tony Shoe Repair", "location"=>"208 W 35th St New York, NY 10001", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Cobbler Express Shoe Repair", "location"=>"60 Wall St New York, NY 10005", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Chelsea Cobbler", "location"=>"196 7th Ave New York, NY 10011", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Leather Spa - Downtown", "location"=>"28 John St New York, NY 10038", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Ralph's Shoe Repair", "location"=>"59 Beach St New York, NY 10013", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Shoe Repair And Shine", "location"=>"206 Varick St New York, NY 10014", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"V Zeev Express Shoe Repair", "location"=>"686 Flatbush Ave Brooklyn, NY 11226", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Shoe Repair", "location"=>"205 W 57st Manhattan, NY 10019", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Master Shoe Repair", "location"=>"90 Worth St New York, NY 11013", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Express Shoe Repair", "location"=>"59 Franklin St New York, NY 10013", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Arnold's Custom Shoe Repair", "location"=>"168 E 44th St New York, NY 10017", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Alex Shoe Repair", "location"=>"166 W 27th St New York, NY 10001", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Friends Shoe Repair & Tailoring", "location"=>"166 E 28th St New York, NY 10016", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Drago Shoe Repair", "location"=>"625 8th Ave Bsmt 2 New York, NY 10018", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Jacob's Shoe Repair", "location"=>"25 Maiden Ln New York, NY 10038", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Top Shoe Repair", "location"=>"600 5th Ave Frnt New York, NY 10020", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Anthony's Shoe Repair", "location"=>"153 E 43rd St New York, NY 10017", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Soleman", "location"=>"201-235 W 33rd St New York, NY 10001", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Steve Express Shoe Repair", "location"=>"311 E 14th St New York, NY 10003", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Eddie's Shoe Repair", "location"=>"30 Rockefeller Plz New York, NY 10112", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Leather Spa", "location"=>"55 W 55th St New York, NY 10019", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Giovanni D'Italia Shoe Repair", "location"=>"266 7th St Hoboken, NJ 07030", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
Plan.create("name"=>"Jim's Shoe Repair", "location"=>"50 E 59th St New York, NY 10022", "category"=>nil, "user_id"=>nil, "risk_level_id"=>nil)
